"""This module contains functions for resetting the sensor to a fixed position.

@author: f.hader
"""

import numpy as np

__all__ = []


def reset_offset_mu_sens(dqd_sim: "Simulation",
                         target_mu_sens: float,
                         sweep_range_g1: np.ndarray,
                         sweep_range_g2: np.ndarray, ):
    """
    Helper function to reset the sensor offset mu sens before measuring a CSD.

    Can be used to reset the sensor to the steepest point before each CSD measurement. For example, this applies to
    configs generated by sample_random_variations_v3_config with the set_sensor_potential_offset_to_steepest_point
    option, which creates a configuration where the offset corresponds to the steepest point when no voltages are
    applied.

    **Warning**: This alters the provided Simulation object! Make sure to store the previous sensor offset if you want
    to re-use it later to reset the sensor to this point again.

    Args:
        dqd_sim (Simulation): SimCATS Simulation object, of which the offset_mu_sens should be adjusted, so that the
            sensor has the specified target_mu_sens at the initial sweep voltages.
        target_mu_sens: The target mu sens to be reached at the initial sweep voltages.
        sweep_range_g1 (np.ndarray): Voltage sweep range of (plunger) gate 1 (second-/x-axis). \n
            Example: \n
            [min_V1, max_V1]
        sweep_range_g2 (np.ndarray): Voltage sweep range of (plunger) gate 2 (first-/y-axis). \n
            Example: \n
            [min_V2, max_V2]
    """
    # calculate potential to reset offset_mu_sens
    occupations, _ = dqd_sim.ideal_csd_config.get_csd_data(volt_limits_g1=sweep_range_g1,
                                                           volt_limits_g2=sweep_range_g2,
                                                           resolution=2)
    potentials = dqd_sim.sensor.sensor_potential(occupations, sweep_range_g1, sweep_range_g2)
    # the new offset is calculated as follows: target_offset - (potentials[0] - current_offset)
    dqd_sim.sensor.offset_mu_sens = target_mu_sens - (potentials[0] - dqd_sim.sensor.offset_mu_sens)
